package EstadoApp;


/**
* EstadoApp/Estado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* viernes 25 de mayo de 2018 09H10' COT
*/

public interface Estado extends EstadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Estado
