package EstadoApp;

/**
* EstadoApp/EstadoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* viernes 25 de mayo de 2018 09H10' COT
*/

public final class EstadoHolder implements org.omg.CORBA.portable.Streamable
{
  public EstadoApp.Estado value = null;

  public EstadoHolder ()
  {
  }

  public EstadoHolder (EstadoApp.Estado initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EstadoApp.EstadoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EstadoApp.EstadoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EstadoApp.EstadoHelper.type ();
  }

}
