package GeneroApp;


/**
* GeneroApp/GeneroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* viernes 25 de mayo de 2018 09H10' COT
*/

public interface GeneroOperations 
{
  boolean insertarGenero (int id, String nombre);
  boolean eliminarGenero (int id);
  boolean actualizarGenero (int id, String nombre);
  void shutdown ();
} // interface GeneroOperations
