package GeneroApp;


/**
* GeneroApp/Genero.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* viernes 25 de mayo de 2018 09H10' COT
*/

public interface Genero extends GeneroOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Genero
