package GeneroApp;

/**
* GeneroApp/GeneroHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Genero.idl
* viernes 25 de mayo de 2018 09H10' COT
*/

public final class GeneroHolder implements org.omg.CORBA.portable.Streamable
{
  public GeneroApp.Genero value = null;

  public GeneroHolder ()
  {
  }

  public GeneroHolder (GeneroApp.Genero initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GeneroApp.GeneroHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GeneroApp.GeneroHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GeneroApp.GeneroHelper.type ();
  }

}
