package PersonaApp;


/**
* PersonaApp/Persona.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Persona.idl
* viernes 25 de mayo de 2018 09H09' COT
*/

public interface Persona extends PersonaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Persona
